const String baseUrl = "http://beta.dhm.gov.np:8080/api";
const String baseUrlSecond =
    "https://webapiserver.dhm.gov.np/api/cities?domain=Nepal";
const String airporListUrl = "$baseUrl/getAirportList";
const String tafsRawUrl = '$baseUrl/getTAFData/raw/';
const String tafsDecodedUrl = '$baseUrl/getTAFData/decoded/';
const String metaDataDecodedUrl = '$baseUrl/getMetarData/decoded/';
const String metaDataRawUrl = '$baseUrl/getMetarData/raw/';
const String sigmetsDataUrl = '$baseUrl/getSigmetsData/';
const String gametDataUrl = '$baseUrl/getGametData/';
const String airmetDataUrl = '$baseUrl/getAirmetData/';
const String opmetDataUrl = '$baseUrl/getOpmetData/';
const String ashtamsDataUrl = '$baseUrl/getAshtamsData/';
const String satelliteImageDataUrl = '$baseUrl/satellite/';
const String loginUrl = '$baseUrl/login/login/';
const String lightingDataUrl = '$baseUrl/lightning/';
const String privacyPolicyUrl = '$baseUrl/getPrivacy/';
// const String metaDataDecodedUrl = '$baseUrl/api/getMetarData/decoded/';
