name: aviation_met_nepal
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"



dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  flutter_osm_plugin: ^0.28.0+1
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^0.23.0+1
  google_maps_flutter: ^2.1.3
  http: ^0.13.4
  intl: ^0.17.0
  provider: ^6.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/

  
